// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9h43tWWwZYpMz3WpK_k7FMfn9IWrzH0',
    appId: '1:135450583677:web:22f53c64902d94ed5fc714',
    messagingSenderId: '135450583677',
    projectId: 'revive-3825c',
    authDomain: 'revive-3825c.firebaseapp.com',
    storageBucket: 'revive-3825c.appspot.com',
    measurementId: 'G-Y8YVMJ6G14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotlCjjhiaAKpr4rN9g8Cj-Tr2lpJYJd0',
    appId: '1:135450583677:android:9a30e94a8d4db1675fc714',
    messagingSenderId: '135450583677',
    projectId: 'revive-3825c',
    storageBucket: 'revive-3825c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKu7C0qA1Nrkm9J7jmD3lJDIUkYg9KwY8',
    appId: '1:135450583677:ios:0a84977bed778b9f5fc714',
    messagingSenderId: '135450583677',
    projectId: 'revive-3825c',
    storageBucket: 'revive-3825c.appspot.com',
    iosBundleId: 'com.example.revive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKu7C0qA1Nrkm9J7jmD3lJDIUkYg9KwY8',
    appId: '1:135450583677:ios:0a84977bed778b9f5fc714',
    messagingSenderId: '135450583677',
    projectId: 'revive-3825c',
    storageBucket: 'revive-3825c.appspot.com',
    iosBundleId: 'com.example.revive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb9h43tWWwZYpMz3WpK_k7FMfn9IWrzH0',
    appId: '1:135450583677:web:b5f6f3f8551d8b895fc714',
    messagingSenderId: '135450583677',
    projectId: 'revive-3825c',
    authDomain: 'revive-3825c.firebaseapp.com',
    storageBucket: 'revive-3825c.appspot.com',
    measurementId: 'G-6XGSNQ586N',
  );
}
